name: CI CalculatorMVS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Se configura JDK 25 (Temurin)
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "25"
          check-latest: true
          cache: gradle

      - name: Asegura que gradlew sea ejecutable
        run: chmod +x ./gradlew
        working-directory: ./calculatorMVS

      - name: Compilación
        run: ./gradlew compileJava --no-daemon
        working-directory: ./calculatorMVS

      - name: Pruebas unitarias
        run: ./gradlew test --no-daemon
        working-directory: ./calculatorMVS

      - name: Generar informe
        run: ./gradlew jacocoTestReport --no-daemon
        working-directory: ./calculatorMVS

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: calculatorMVS/build/reports/jacoco/test/html

      - name: Verificar cobertura
        run: ./gradlew jacocoTestCoverageVerification --no-daemon
        working-directory: ./calculatorMVS

      - name: Ejecutar análisis
        run: ./gradlew checkstyleMain --no-daemon
        working-directory: ./calculatorMVS

      - name: Subir informe Checkstyle
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: calculatorMVS/build/reports/checkstyle