name: CI CalculatorAAN
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Se configura JDK 25 (Temurin)
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "25"
          check-latest: true
          cache: gradle

    - name: Asegura que gradlew sea ejecutable
    run: chmod +x ./gradlew
    
  - name: Compilación
  run: ./gradlew compileJava –no-daemon
